apiVersion: v1
kind: Service
metadata:
  name: {{ include "trow.fullname" . }}
  labels:
    {{- include "trow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "trow.selectorLabels" . | nindent 4 }}
