{{- range $t, $v := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trow.fullname" $ }}{{ ternary "" "-node" (eq $t "clusterIP") }}
  labels:
    {{- include "trow.labels" $ | nindent 4 }}
spec:
  type: {{ title $t }}
  ports:
    {{- $v | toYaml | nindent 4 }}
  selector:
    {{- include "trow.selectorLabels" $ | nindent 4 }}
{{ end }}